polsol.cc/Models/Company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.RegularExpressions;

namespace polsol.cc.Models
{
    public enum CompanyCatagory
    {
        Cardinals
        ,Cubs
        ,Brewers
    }

    public class Company
    {
        public int ID { get; set; }
        [StringLength(50), Required]
        public string Name { get; set; }
        [StringLength(15), Required]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        public CompanyCatagory? Catagory { get; set; }

        public ICollection<Contact> Contacts { get; set; }

        [NotMapped]
        public string FormattedPhoneNumber {
            get
            {
                return Regex.Replace(PhoneNumber, @"(\d{3})(\d{3})(\d{4})", "$1-$2-$3");
            }
            set
            {
                PhoneNumber = new string(value.Where(c => char.IsDigit(c)).ToArray());
            }
        }
    }
}

polsol.cc/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using polsol.cc.Data;
using polsol.cc.Models;

namespace polsol.cc.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly CompanyContext _context;

        public CompaniesController(CompanyContext context)
        {
            _context = context;
        }

        // GET: Companies
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CatSortParm"] = sortOrder =="cat" ? "cat_desc" : "cat";
            ViewData["CurrentFilter"] = searchString;

            var companies = from c in _context.Companies
                            select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                companies = companies.Where(c => c.PhoneNumber.Contains(searchString));
            }

            switch(sortOrder)
            {
                case "name_desc":
                    companies = companies.OrderByDescending(c => c.Name);
                    break;
                case "cat":
                    companies = companies.OrderBy(c => c.Catagory);
                    break;
                case "cat_desc":
                    companies = companies.OrderByDescending(c => c.Catagory);
                    break;
                default:
                    companies = companies.OrderBy(s => s.Name);
                    break;
            }

            return View(await companies.AsNoTracking().ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id, string sortOrder)
        {
            ViewData["FirstNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "first_desc" : "";
            ViewData["LastNameSortParm"] = sortOrder == "last" ? "last_desc" : "last";

            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .Include(c => c.Contacts)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (company == null)
            {
                return NotFound();
            }

            switch(sortOrder)
            {
                case "first_desc":
                    company.Contacts = company.Contacts.OrderByDescending(c => c.FirstName).ToList();
                    break;
                case "last":
                    company.Contacts = company.Contacts.OrderBy(c => c.LastName).ToList();
                    break;
                case "last_desc":
                    company.Contacts = company.Contacts.OrderByDescending(c => c.LastName).ToList();
                    break;
                default:
                    company.Contacts = company.Contacts.OrderBy(c => c.FirstName).ToList();
                    break;
            }

            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,FormattedPhoneNumber,Catagory")] Company company)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(company);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch ( DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " +
                            "Try again, and if the problem persists " +
                            "see your system administrator.");
            }            
            return View(company);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.SingleOrDefaultAsync(m => m.ID == id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyToUpdate = await _context.Companies.SingleOrDefaultAsync(s => s.ID == id);
            if (await TryUpdateModelAsync<Company>(
                companyToUpdate,
                "",
                c => c.Name, c => c.PhoneNumber, cc => cc.Catagory))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
            }
            return View(companyToUpdate);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .Include(c => c.Contacts)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (company == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _context.Companies
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (company == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                _context.Companies.Remove(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
            
        }

        private bool CompanyExists(int id)
        {
            return _context.Companies.Any(e => e.ID == id);
        }
    }
}

polsol.cc/Controllers/ContactsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using polsol.cc.Data;
using polsol.cc.Models;

namespace polsol.cc.Controllers
{
    public class ContactsController : Controller
    {
        private readonly CompanyContext _context;

        public ContactsController(CompanyContext context)
        {
            _context = context;
        }

        // GET: Contacts
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["FirstNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "first_name_desc" : "";
            ViewData["LastNameSortParm"] = sortOrder == "last" ? "last_name_desc" : "last";
            ViewData["CompSortParm"] = sortOrder == "comp" ? "comp_desc" : "comp";

            var contacts = _context.Contacts.Include(c => c.Company);
            var sortedContacts = contacts.OrderBy(c => c.FirstName);

            switch (sortOrder)
            {
                case "first_name_desc":
                    sortedContacts = contacts.OrderByDescending(c => c.FirstName);
                    break;
                case "last":
                    sortedContacts = contacts.OrderBy(c => c.LastName);
                    break;
                case "last_name_desc":
                    sortedContacts = contacts.OrderByDescending(c => c.LastName);
                    break;
                case "comp":
                    sortedContacts = contacts.OrderBy(c => c.Company.Name);
                    break;
                case "comp_desc":
                    sortedContacts = contacts.OrderByDescending(c => c.Company.Name);
                    break;
            }
            return View(await sortedContacts.AsNoTracking().ToListAsync());
        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts
                .Include(c => c.Company)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contacts/Create
        public IActionResult Create(int? companyId)
        {
            ViewData["CompanyId"] = new SelectList(_context.Companies, "ID", "Name", companyId);
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompanyId,FirstName,LastName")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contact);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "ID", "Name", contact.CompanyId);
            return View(contact);
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts.SingleOrDefaultAsync(m => m.ID == id);
            if (contact == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "ID", "Name", contact.CompanyId);
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,CompanyId,FirstName,LastName")] Contact contact)
        {
            if (id != contact.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contact);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactExists(contact.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", contact.CompanyId);
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts
                .Include(c => c.Company)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contact = await _context.Contacts.SingleOrDefaultAsync(m => m.ID == id);
            _context.Contacts.Remove(contact);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactExists(int id)
        {
            return _context.Contacts.Any(e => e.ID == id);
        }
    }
}

polsol.cc/Views/Companies/Create.cshtml
@model polsol.cc.Models.Company

@{
    ViewData["Title"] = "Create";
}

<h2>Create Company</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="FormattedPhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catagory" class="control-label"></label>
                <select asp-for="Catagory" asp-items="Html.GetEnumSelectList<CompanyCatagory>()" class="form-control" >
                    <option value="">-- Not specified --</option>
                </select>
                <span asp-validation-for="Catagory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

polsol.cc/Views/Companies/Delete.cshtml
@model polsol.cc.Models.Company

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete Company</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />

    <dl class="dl-horizontal">
        @Html.Partial("_CompanyDetails.cshtml", Model)
        <dd>
            <table class="table">
                <tr>
                    <th>
                        First Name
                    </th>
                    <th>
                        Last Name
                    </th>
                </tr>
                @foreach (var item in Model.Contacts)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

polsol.cc/Views/Companies/Details.cshtml
@model polsol.cc.Models.Company

@{
    ViewData["Title"] = "Details";
}

<h2>Company Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        @Html.Partial("_CompanyDetails.cshtml", Model)
        <dd>
            <table class="table">
                <tr>
                    <th>
                        <a asp-action="Details" asp-route-id="@Model.ID" asp-route-sortOrder="@ViewData["FirstNameSortParm"]">First Name</a>
                    </th>
                    <th>
                        <a asp-action="Details" asp-route-id="@Model.ID" asp-route-sortOrder="@ViewData["LastNameSortParm"]">Last Name</a>
                    </th>
                </tr>
                @foreach (var item in Model.Contacts)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-area="" asp-controller="Contacts" asp-action="Create" asp-route-companyId="@Model.ID">Create New Contact</a> |
    <a asp-action="Index">Back to List</a>
</div>

polsol.cc/Views/Companies/Edit.cshtml
@model polsol.cc.Models.Company

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Company</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="FormattedPhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catagory" class="control-label"></label>
                <select asp-for="Catagory" asp-items="Html.GetEnumSelectList<CompanyCatagory>()" class="form-control">
                    <option value="">-- Not specified --</option>
                </select>
                <span asp-validation-for="Catagory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

polsol.cc/Views/Companies/Index.cshtml
@model IEnumerable<polsol.cc.Models.Company>

@{
    ViewData["Title"] = "Index";
}

<h2>Company Master List</h2>
<form asp-action="Index" method="get">
    <p>
        <div class="btn-toolbar" role="toolbar" aria-label="Company Toolbar">
            <div class="btn-group" role="group" aria-label="First group">
                <input type="submit" asp-action="Create" value="Create" class="btn btn-default" />
            </div>
            <div class="btn-group" role="group" aria-label="Second group" id="company-edit-btn-group">
                <input type="submit" asp-action="Edit" value="Edit" class="btn btn-default" disabled="disabled"/>
                <input type="submit" asp-action="Details" value="Detail" class="btn btn-default"  disabled="disabled" />
                <input type="submit" asp-action="Delete" value="Delete" class="btn btn-default"  disabled="disabled"/>
            </div>
        </div>
    </p>
    <div class="form-actions no-color">
        <p>
            Find by phone number: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>
<table class="table" id="company-table">
    <thead>
        <tr>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">@Html.DisplayNameFor(model => model.Name)</a>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["CatSortParm"]">@Html.DisplayNameFor(model => model.Catagory)</a>
                </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr data-id="@item.ID">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FormattedPhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Catagory)
            </td>
        </tr>
}
    </tbody>
</table>

polsol.cc/Views/Companies/_CompanyDetails.cshtml
@model polsol.cc.Models.Company

<dt>
    @Html.DisplayNameFor(model => model.Name)
</dt>
<dd>
    @Html.DisplayFor(model => model.Name)
</dd>
<dt>
    @Html.DisplayNameFor(model => model.PhoneNumber)
</dt>
<dd>
    @Html.DisplayFor(model => model.FormattedPhoneNumber)
</dd>
<dt>
    @Html.DisplayNameFor(model => model.Catagory)
</dt>
<dd>
    @Html.DisplayFor(model => model.Catagory)
</dd>
<dt>
    @Html.DisplayNameFor(model => model.Contacts)
</dt>
    